import json
import logging
import os
import re
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

import sqlparse
from dotenv import load_dotenv
from sqlalchemy import text
from sqlalchemy.exc import SQLAlchemyError

from database import get_engine, get_schema, get_sql_dialect

load_dotenv()

# Change MODEL_NAME in .env to switch models.
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434").rstrip("/")
MODEL_NAME = os.getenv("MODEL_NAME", "qwen3:8b")
OLLAMA_TIMEOUT_SECONDS = int(os.getenv("OLLAMA_TIMEOUT_SECONDS", "600"))
OLLAMA_KEEP_ALIVE = os.getenv("OLLAMA_KEEP_ALIVE", "30m")
OLLAMA_MAX_TOKENS = int(os.getenv("OLLAMA_MAX_TOKENS", "256"))

logger = logging.getLogger(__name__)


class SQLGenerationError(Exception):
    """Raised when a SQL query cannot be generated by the local model."""

    status_code = 502


class OllamaUnavailableError(SQLGenerationError):
    """Raised when the local Ollama server cannot be reached."""

    status_code = 503


class OllamaModelNotFoundError(SQLGenerationError):
    """Raised when the configured Ollama model is not installed."""

    status_code = 503


class OllamaTimeoutError(SQLGenerationError):
    """Raised when Ollama does not answer before the configured timeout."""

    status_code = 504


class InvalidGeneratedSQLError(SQLGenerationError):
    """Raised when Ollama output is empty or is not executable SQL."""

    status_code = 422


def clean_sql_output(response_text):
    """Remove Markdown wrappers while preserving the complete SQL statement."""
    if not isinstance(response_text, str):
        return ""

    clean_query = response_text.strip()
    clean_query = re.sub(
        r"^\s*```(?:sql|mysql)?\s*",
        "",
        clean_query,
        flags=re.IGNORECASE,
    )
    clean_query = re.sub(r"\s*```\s*$", "", clean_query)
    clean_query = clean_query.replace("```sql", "").replace("```SQL", "").replace("```", "")

    return clean_query.strip()


def extract_sql_statement(response_text):
    """Return a standalone SQL statement from a model response, if present.

    Some model/runtime combinations emit reasoning before the requested SQL.
    Looking for a statement at the beginning of a line avoids treating prose
    such as "select the name column" as SQL.
    """
    clean_query = clean_sql_output(response_text)
    is_valid, _ = validate_sql_query(clean_query)
    if is_valid:
        return clean_query

    statement_match = re.search(
        r"(?ims)^\s*(SELECT|INSERT|UPDATE|DELETE)\b.*?;",
        clean_query,
    )
    if statement_match:
        return statement_match.group(0).strip()

    return clean_query


def validate_sql_query(sql_query):
    """Validate that the result is one executable SQL statement."""
    try:
        parsed = sqlparse.parse(sql_query)

        if not parsed or len(parsed) != 1 or not sql_query.strip():
            return False, "Invalid SQL syntax."

        statement_type = parsed[0].get_type()
        if statement_type not in {"SELECT", "INSERT", "UPDATE", "DELETE"}:
            return (
                False,
                "Only executable SELECT, INSERT, UPDATE, and DELETE statements are allowed.",
            )

        return True, None
    except Exception as exc:
        return False, str(exc)


def generate_sql_query(natural_language_query):
    """Convert a natural-language request into an optimized MySQL query."""
    if not natural_language_query or not natural_language_query.strip():
        raise SQLGenerationError("The natural language query cannot be empty.")

    try:
        schema = get_schema()
    except Exception as exc:
        raise SQLGenerationError(f"Could not read the database schema: {exc}") from exc

    schema_text = "\n".join(
        f"{table}: {', '.join(columns)}"
        for table, columns in schema.items()
    )

    dialect = get_sql_dialect().upper()
    dialect_rules = ""
    if dialect == "SQLITE":
        dialect_rules = (
            "- SQLite syntax: use LIMIT <number> after ORDER BY to limit rows.\n"
            "- Never use TOP, which is not valid SQLite syntax.\n"
        )

    prompt = f"""You are an expert {dialect} SQL generator.

Database Schema:
{schema_text}

Rules:
- Return a JSON object with exactly one key: "sql".
- The "sql" value must be one executable SQL statement.
- No explanation or markdown.
- Use only tables present in the schema.
- Generate optimized SQL.
- Use JOIN instead of subqueries where appropriate.
- Use SUM, AVG, COUNT, GROUP BY, or other aggregation only when the user explicitly asks for an aggregate, total, average, count, or grouping.
- For "top", "highest", or "largest" requests without an explicit aggregate, return individual rows ordered by the requested column.

Dialect-specific rules:
{dialect_rules}

User Question:
{natural_language_query.strip()}
/no_think

SQL:"""

    payload = json.dumps(
        {
        "model": MODEL_NAME,
            "format": {
                "type": "object",
                "properties": {"sql": {"type": "string"}},
                "required": ["sql"],
                "additionalProperties": False,
            },
            "messages": [{"role": "user", "content": prompt}],
            "stream": False,
            "think": False,
            "keep_alive": OLLAMA_KEEP_ALIVE,
            "options": {
                "temperature": 0,
                "num_predict": OLLAMA_MAX_TOKENS,
            },
        }
    ).encode("utf-8")

    request = Request(
        f"{OLLAMA_BASE_URL}/api/chat",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urlopen(request, timeout=OLLAMA_TIMEOUT_SECONDS) as response:
            body = json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        if exc.code == 404:
            raise OllamaModelNotFoundError(
                f"Ollama model '{MODEL_NAME}' is not installed. "
                f"Run: ollama pull {MODEL_NAME}"
            ) from exc

        raise SQLGenerationError(f"Ollama returned HTTP {exc.code}.") from exc
    except URLError as exc:
        raise OllamaUnavailableError(
            f"Cannot reach Ollama at {OLLAMA_BASE_URL}. "
            "Start it with: ollama serve"
        ) from exc
    except TimeoutError as exc:
        raise OllamaTimeoutError(
            "Ollama request timed out while generating SQL."
        ) from exc
    except json.JSONDecodeError as exc:
        raise SQLGenerationError("Ollama returned an invalid response.") from exc

    message = body.get("message", {})
    raw_response = message.get("content", "")
    logger.warning(
        "Ollama chat completed: model=%s done_reason=%s thinking=%r raw_response=%r",
        body.get("model", MODEL_NAME),
        body.get("done_reason"),
        message.get("thinking", ""),
        raw_response,
    )

    try:
        structured_output = json.loads(raw_response)
        sql_value = structured_output.get("sql", "") if isinstance(structured_output, dict) else ""
        clean_query = clean_sql_output(sql_value)
    except json.JSONDecodeError:
        clean_query = extract_sql_statement(raw_response)

    if not clean_query:
        raise InvalidGeneratedSQLError("Ollama returned an empty SQL response.")

    is_valid, error_message = validate_sql_query(clean_query)
    if not is_valid:
        if body.get("done_reason") == "length":
            raise InvalidGeneratedSQLError(
                "Ollama reached its output-token limit before returning valid SQL. "
                "Increase OLLAMA_MAX_TOKENS or use a non-thinking SQL model."
            )
        raise InvalidGeneratedSQLError(
            f"Ollama generated invalid SQL: {error_message}"
        )

    return clean_query


def suggest_index(sql_query):
    """Suggest indexes for the executed SQL query."""
    try:
        with get_engine().connect() as connection:
            explain_query = f"EXPLAIN {sql_query}"
            result = connection.execute(text(explain_query))
            execution_plan = result.fetchall()

        print("\nQuery Execution Plan:")
        for row in execution_plan:
            print(row)

        return "Consider adding an index on frequently used WHERE conditions."
    except Exception as exc:
        return f"Could not generate execution plan: {exc}"


def execute_query(sql_query):
    """Execute a validated SQL query."""
    is_valid, error_msg = validate_sql_query(sql_query)
    if not is_valid:
        print(f"SQL Validation Error: {error_msg}")
        return None

    try:
        with get_engine().connect() as connection:
            result = connection.execute(text(sql_query))
            fetched_results = result.fetchall() if result.returns_rows else []

        index_suggestion = suggest_index(sql_query)
        results = [dict(row._mapping) for row in fetched_results]

        return {"results": results, "optimization_tips": index_suggestion}
    except SQLAlchemyError as exc:
        print(f"SQL Execution Error: {exc}")
        return None


execute_sql_query = execute_query
generate_sql = generate_sql_query


if __name__ == "__main__":
    user_input = input("Enter your natural language query: ")
    sql_query = generate_sql_query(user_input)

    if sql_query:
        print(f"\nGenerated SQL Query:\n{sql_query}")

        execution_result = execute_query(sql_query)
        if execution_result:
            print("\nQuery Results:")
            for row in execution_result["results"]:
                print(row)
            print("\nOptimization Tips:", execution_result["optimization_tips"])
        else:
            print("Failed to execute the SQL query.")
    else:
        print("Failed to generate a valid SQL query.")
